"""P2 domain core

Revision ID: 0002_domain_core
Revises: 0001_baseline
Create Date: 2026-08-08 13:16:15.930415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_domain_core'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('totp_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_events',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('actor_label', sa.String(length=254), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before', sa.Text(), nullable=False),
    sa.Column('after', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_audit_org_sequence', ['organization_id', 'sequence'], unique=True)

    op.create_table('contract_parties',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('party_role', sa.String(length=32), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_parties_organization_id'), ['organization_id'], unique=False)

    op.create_table('cost_codes',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('division', sa.String(length=8), nullable=False),
    sa.Column('is_seeded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_cost_code')
    )
    with op.batch_alter_table('cost_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_codes_organization_id'), ['organization_id'], unique=False)

    op.create_table('invitations',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token_hash'), ['token_hash'], unique=True)

    op.create_table('memberships',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('retainage_rules',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('rate_work_bp', sa.Integer(), nullable=False),
    sa.Column('rate_stored_bp', sa.Integer(), nullable=False),
    sa.Column('reduction_threshold_bp', sa.Integer(), nullable=True),
    sa.Column('reduced_rate_bp', sa.Integer(), nullable=True),
    sa.Column('statutory_cap_bp', sa.Integer(), nullable=True),
    sa.Column('statute_citation', sa.String(length=255), nullable=False),
    sa.Column('cap_enforcement', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retainage_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retainage_rules_organization_id'), ['organization_id'], unique=False)

    op.create_table('projects',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('jurisdiction_state', sa.String(length=2), nullable=False),
    sa.Column('is_public_work', sa.Boolean(), nullable=False),
    sa.Column('is_residential', sa.Boolean(), nullable=False),
    sa.Column('stories', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_party_id', sa.String(length=32), nullable=True),
    sa.Column('architect_party_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['architect_party_id'], ['contract_parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_party_id'], ['contract_parties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'number', name='uq_project_number')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)

    op.create_table('prime_contracts',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('original_contract_sum_cents', sa.BigInteger(), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=True),
    sa.Column('substantial_completion_date', sa.Date(), nullable=True),
    sa.Column('period_convention', sa.String(length=32), nullable=False),
    sa.Column('billing_day_of_month', sa.Integer(), nullable=False),
    sa.Column('retainage_rule_id', sa.String(length=32), nullable=True),
    sa.Column('stored_materials_allowed', sa.Boolean(), nullable=False),
    sa.Column('offsite_stored_allowed', sa.Boolean(), nullable=False),
    sa.Column('bonding_required_for_stored', sa.Boolean(), nullable=False),
    sa.Column('default_form_style', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retainage_rule_id'], ['retainage_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prime_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prime_contracts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prime_contracts_project_id'), ['project_id'], unique=False)

    op.create_table('schedules_of_values',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('prime_contract_id', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prime_contract_id'], ['prime_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prime_contract_id', 'revision', name='uq_sov_revision')
    )
    with op.batch_alter_table('schedules_of_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_of_values_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_of_values_prime_contract_id'), ['prime_contract_id'], unique=False)

    op.create_table('sov_lines',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('schedule_id', sa.String(length=32), nullable=False),
    sa.Column('item_no', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('csi_code', sa.String(length=32), nullable=False),
    sa.Column('cost_code', sa.String(length=32), nullable=False),
    sa.Column('group', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('base_scheduled_value_cents', sa.BigInteger(), nullable=False),
    sa.Column('co_adjustment_cents', sa.BigInteger(), nullable=False),
    sa.Column('current_scheduled_value_cents', sa.BigInteger(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('quantity_milli', sa.Integer(), nullable=True),
    sa.Column('unit_price_cents', sa.BigInteger(), nullable=True),
    sa.Column('retainage_rate_bp', sa.Integer(), nullable=True),
    sa.Column('is_co_line', sa.Boolean(), nullable=False),
    sa.Column('is_general_conditions', sa.Boolean(), nullable=False),
    sa.Column('is_allowance', sa.Boolean(), nullable=False),
    sa.Column('allowance_balance_cents', sa.BigInteger(), nullable=True),
    sa.Column('source_change_order_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules_of_values.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sov_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sov_lines_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sov_lines_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sov_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sov_lines_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_sov_lines_organization_id'))

    op.drop_table('sov_lines')
    with op.batch_alter_table('schedules_of_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_of_values_prime_contract_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_of_values_organization_id'))

    op.drop_table('schedules_of_values')
    with op.batch_alter_table('prime_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prime_contracts_project_id'))
        batch_op.drop_index(batch_op.f('ix_prime_contracts_organization_id'))

    op.drop_table('prime_contracts')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))

    op.drop_table('projects')
    with op.batch_alter_table('retainage_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retainage_rules_organization_id'))

    op.drop_table('retainage_rules')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_invitations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))

    op.drop_table('invitations')
    with op.batch_alter_table('cost_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_codes_organization_id'))

    op.drop_table('cost_codes')
    with op.batch_alter_table('contract_parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_parties_organization_id'))

    op.drop_table('contract_parties')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_sequence')
        batch_op.drop_index(batch_op.f('ix_audit_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
