"""P3 requisition engine

Revision ID: 0003_requisition
Revises: 0002_domain_core
Create Date: 2026-08-08 16:23:07.364225

"""
from alembic import op
import sqlalchemy as sa

import massingbill.models.base  # noqa: F401  (UtcDateTime is referenced below)


# revision identifiers, used by Alembic.
revision = '0003_requisition'
down_revision = '0002_domain_core'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potential_change_orders',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('prime_contract_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('proposed_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('pricing_backup', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prime_contract_id'], ['prime_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('potential_change_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_potential_change_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_potential_change_orders_prime_contract_id'), ['prime_contract_id'], unique=False)

    op.create_table('applications',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('prime_contract_id', sa.String(length=32), nullable=False),
    sa.Column('schedule_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('form_style', sa.String(length=32), nullable=False),
    sa.Column('line1_original_sum', sa.BigInteger(), nullable=False),
    sa.Column('line2_net_co', sa.BigInteger(), nullable=False),
    sa.Column('line3_contract_sum_to_date', sa.BigInteger(), nullable=False),
    sa.Column('line4_completed_stored', sa.BigInteger(), nullable=False),
    sa.Column('line5a_retainage_work', sa.BigInteger(), nullable=False),
    sa.Column('line5b_retainage_stored', sa.BigInteger(), nullable=False),
    sa.Column('line5_total_retainage', sa.BigInteger(), nullable=False),
    sa.Column('line6_earned_less_retainage', sa.BigInteger(), nullable=False),
    sa.Column('line7_previous_certificates', sa.BigInteger(), nullable=False),
    sa.Column('line8_current_payment_due', sa.BigInteger(), nullable=False),
    sa.Column('line9_balance_to_finish', sa.BigInteger(), nullable=False),
    sa.Column('co_summary_prev_additions', sa.BigInteger(), nullable=False),
    sa.Column('co_summary_prev_deductions', sa.BigInteger(), nullable=False),
    sa.Column('co_summary_this_additions', sa.BigInteger(), nullable=False),
    sa.Column('co_summary_this_deductions', sa.BigInteger(), nullable=False),
    sa.Column('submitted_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('submitted_by_id', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prime_contract_id'], ['prime_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules_of_values.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prime_contract_id', 'number', name='uq_application_number')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_prime_contract_id'), ['prime_contract_id'], unique=False)

    op.create_table('application_lines',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('sov_line_id', sa.String(length=32), nullable=False),
    sa.Column('item_no', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('csi_code', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('col_c_scheduled_value', sa.BigInteger(), nullable=False),
    sa.Column('col_d_previous', sa.BigInteger(), nullable=False),
    sa.Column('col_e_this_period', sa.BigInteger(), nullable=False),
    sa.Column('col_f_stored', sa.BigInteger(), nullable=False),
    sa.Column('col_g_completed_stored', sa.BigInteger(), nullable=False),
    sa.Column('col_h_balance', sa.BigInteger(), nullable=False),
    sa.Column('col_i_retainage', sa.BigInteger(), nullable=False),
    sa.Column('percent_complete_bp', sa.Integer(), nullable=False),
    sa.Column('is_co_line', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sov_line_id'], ['sov_lines.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_lines_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_lines_organization_id'), ['organization_id'], unique=False)

    op.create_table('application_snapshots',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('taken_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    with op.batch_alter_table('application_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_snapshots_organization_id'), ['organization_id'], unique=False)

    op.create_table('certifications',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('amount_certified_cents', sa.BigInteger(), nullable=False),
    sa.Column('variance_cents', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('certified_by_id', sa.String(length=32), nullable=True),
    sa.Column('certified_by_label', sa.String(length=200), nullable=False),
    sa.Column('certified_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['certified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certifications_organization_id'), ['organization_id'], unique=False)

    op.create_table('change_orders',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('prime_contract_id', sa.String(length=32), nullable=False),
    sa.Column('source_pco_id', sa.String(length=32), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('co_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('time_extension_days', sa.Integer(), nullable=False),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('applies_to_application_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['applies_to_application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prime_contract_id'], ['prime_contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_pco_id'], ['potential_change_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prime_contract_id', 'number', name='uq_change_order_number')
    )
    with op.batch_alter_table('change_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_orders_prime_contract_id'), ['prime_contract_id'], unique=False)

    op.create_table('stored_materials',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('sov_line_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=False),
    sa.Column('first_billed_application_id', sa.String(length=32), nullable=True),
    sa.Column('installed_in_application_id', sa.String(length=32), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('invoice_ref', sa.String(length=120), nullable=False),
    sa.Column('bond_ref', sa.String(length=120), nullable=False),
    sa.Column('insurance_ref', sa.String(length=120), nullable=False),
    sa.Column('stored_on', sa.Date(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['first_billed_application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['installed_in_application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sov_line_id'], ['sov_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stored_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_materials_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_materials_sov_line_id'), ['sov_line_id'], unique=False)

    op.create_table('change_order_lines',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('change_order_id', sa.String(length=32), nullable=False),
    sa.Column('sov_line_id', sa.String(length=32), nullable=True),
    sa.Column('new_item_no', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('csi_code', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['change_order_id'], ['change_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sov_line_id'], ['sov_lines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_order_lines_change_order_id'), ['change_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_order_lines_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_order_lines_organization_id'))
        batch_op.drop_index(batch_op.f('ix_change_order_lines_change_order_id'))

    op.drop_table('change_order_lines')
    with op.batch_alter_table('stored_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_materials_sov_line_id'))
        batch_op.drop_index(batch_op.f('ix_stored_materials_organization_id'))

    op.drop_table('stored_materials')
    with op.batch_alter_table('change_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_orders_prime_contract_id'))
        batch_op.drop_index(batch_op.f('ix_change_orders_organization_id'))

    op.drop_table('change_orders')
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certifications_organization_id'))

    op.drop_table('certifications')
    with op.batch_alter_table('application_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_snapshots_organization_id'))

    op.drop_table('application_snapshots')
    with op.batch_alter_table('application_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_lines_organization_id'))
        batch_op.drop_index(batch_op.f('ix_application_lines_application_id'))

    op.drop_table('application_lines')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_prime_contract_id'))
        batch_op.drop_index(batch_op.f('ix_applications_organization_id'))

    op.drop_table('applications')
    with op.batch_alter_table('potential_change_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_potential_change_orders_prime_contract_id'))
        batch_op.drop_index(batch_op.f('ix_potential_change_orders_organization_id'))

    op.drop_table('potential_change_orders')
    # ### end Alembic commands ###
