"""P6 waivers, signatures and compliance

Revision ID: 0004_waivers
Revises: 0003_requisition
Create Date: 2026-08-09 08:39:23.741918

"""
from alembic import op
import sqlalchemy as sa

# Custom column types live here. Autogenerate renders them fully qualified
# (massingbill.models.base.UtcDateTime), so the module must be importable or
# every generated migration fails with NameError on first run.
import massingbill.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision = '0004_waivers'
down_revision = '0003_requisition'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiver_templates',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('waiver_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('required_fields', sa.String(length=500), nullable=False),
    sa.Column('is_statutory', sa.Boolean(), nullable=False),
    sa.Column('must_match_exactly', sa.Boolean(), nullable=False),
    sa.Column('notary_required', sa.Boolean(), nullable=False),
    sa.Column('residential_only', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('citation', sa.String(length=500), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'state', 'waiver_type', 'effective_from', name='uq_waiver_template')
    )
    with op.batch_alter_table('waiver_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiver_templates_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiver_templates_state'), ['state'], unique=False)

    op.create_table('compliance_requirements',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('subcontract_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('blocks_payment', sa.Boolean(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('warn_days_before_expiry', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'subcontract_id', 'kind', name='uq_compliance_requirement')
    )
    with op.batch_alter_table('compliance_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_requirements_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_requirements_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_requirements_subcontract_id'), ['subcontract_id'], unique=False)

    op.create_table('compliance_docs',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('requirement_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_docs_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_docs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_docs_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('waiver_instances',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('subcontract_id', sa.String(length=32), nullable=True),
    sa.Column('waiver_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('claimant', sa.String(length=200), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('through_date', sa.Date(), nullable=False),
    sa.Column('rendered_body', sa.Text(), nullable=False),
    sa.Column('rendered_sha256', sa.String(length=64), nullable=False),
    sa.Column('requested_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('signed_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('notarized_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['waiver_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waiver_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiver_instances_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiver_instances_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiver_instances_subcontract_id'), ['subcontract_id'], unique=False)

    op.create_table('signatures',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('waiver_id', sa.String(length=32), nullable=True),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('signer_title', sa.String(length=200), nullable=False),
    sa.Column('signer_email', sa.String(length=254), nullable=False),
    sa.Column('signer_user_id', sa.String(length=32), nullable=True),
    sa.Column('document_sha256', sa.String(length=64), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('signed_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['waiver_id'], ['waiver_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('waiver_id')
    )
    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signatures_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signatures_organization_id'))

    op.drop_table('signatures')
    with op.batch_alter_table('waiver_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiver_instances_subcontract_id'))
        batch_op.drop_index(batch_op.f('ix_waiver_instances_organization_id'))
        batch_op.drop_index(batch_op.f('ix_waiver_instances_application_id'))

    op.drop_table('waiver_instances')
    with op.batch_alter_table('compliance_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_docs_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_docs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_docs_application_id'))

    op.drop_table('compliance_docs')
    with op.batch_alter_table('compliance_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_requirements_subcontract_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_requirements_project_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_requirements_organization_id'))

    op.drop_table('compliance_requirements')
    with op.batch_alter_table('waiver_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiver_templates_state'))
        batch_op.drop_index(batch_op.f('ix_waiver_templates_organization_id'))

    op.drop_table('waiver_templates')
    # ### end Alembic commands ###
