"""P6 subcontracts and payments

Revision ID: 0005_subcontracts
Revises: 0004_waivers
Create Date: 2026-08-09 09:24:01.238520

"""
from alembic import op
import sqlalchemy as sa

# Custom column types live here. Autogenerate renders them fully qualified
# (massingbill.models.base.UtcDateTime), so the module must be importable or
# every generated migration fails with NameError on first run.
import massingbill.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision = '0005_subcontracts'
down_revision = '0004_waivers'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcontracts',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('csi_code', sa.String(length=32), nullable=False),
    sa.Column('original_amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('co_adjustment_cents', sa.BigInteger(), nullable=False),
    sa.Column('retainage_rate_bp', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('executed_on', sa.Date(), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_subcontract_number')
    )
    with op.batch_alter_table('subcontracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcontracts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontracts_project_id'), ['project_id'], unique=False)

    op.create_table('payments',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('joint_payee', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_organization_id'), ['organization_id'], unique=False)

    op.create_table('sub_applications',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('subcontract_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completed_to_date_cents', sa.BigInteger(), nullable=False),
    sa.Column('stored_cents', sa.BigInteger(), nullable=False),
    sa.Column('retainage_cents', sa.BigInteger(), nullable=False),
    sa.Column('previous_payments_cents', sa.BigInteger(), nullable=False),
    sa.Column('payment_due_cents', sa.BigInteger(), nullable=False),
    sa.Column('approved_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=False),
    sa.Column('received_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('approved_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcontract_id'], ['subcontracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subcontract_id', 'number', name='uq_sub_application_number')
    )
    with op.batch_alter_table('sub_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_applications_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sub_applications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sub_applications_subcontract_id'), ['subcontract_id'], unique=False)

    op.create_table('subcontract_lines',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('subcontract_id', sa.String(length=32), nullable=False),
    sa.Column('sov_line_id', sa.String(length=32), nullable=True),
    sa.Column('item_no', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('scheduled_value_cents', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sov_line_id'], ['sov_lines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcontract_id'], ['subcontracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subcontract_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subcontract_lines_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subcontract_lines_subcontract_id'), ['subcontract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcontract_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcontract_lines_subcontract_id'))
        batch_op.drop_index(batch_op.f('ix_subcontract_lines_organization_id'))

    op.drop_table('subcontract_lines')
    with op.batch_alter_table('sub_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_applications_subcontract_id'))
        batch_op.drop_index(batch_op.f('ix_sub_applications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sub_applications_application_id'))

    op.drop_table('sub_applications')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payments_application_id'))

    op.drop_table('payments')
    with op.batch_alter_table('subcontracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subcontracts_project_id'))
        batch_op.drop_index(batch_op.f('ix_subcontracts_organization_id'))

    op.drop_table('subcontracts')
    # ### end Alembic commands ###
