"""P7 api keys and webhooks

Revision ID: 0006_api
Revises: 0005_subcontracts
Create Date: 2026-08-09 12:03:20.273759

"""
from alembic import op
import sqlalchemy as sa

# Custom column types live here. Autogenerate renders them fully qualified
# (massingbill.models.base.UtcDateTime), so the module must be importable or
# every generated migration fails with NameError on first run.
import massingbill.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision = '0006_api'
down_revision = '0005_subcontracts'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('expires_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_api_keys_public_id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_public_id'), ['public_id'], unique=False)

    op.create_table('webhook_subscriptions',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_subscriptions_organization_id'), ['organization_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('subscription_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('next_attempt_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_event'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('webhook_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_subscriptions_organization_id'))

    op.drop_table('webhook_subscriptions')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_public_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_organization_id'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
