"""P6.5 deadline rules and project anchor dates

Revision ID: 0007_deadlines
Revises: 0006_api
Create Date: 2026-08-09 22:07:47.495186

"""
from alembic import op
import sqlalchemy as sa

# Custom column types live here. Autogenerate renders them fully qualified
# (massingbill.models.base.UtcDateTime), so the module must be importable or
# every generated migration fails with NameError on first run.
import massingbill.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision = '0007_deadlines'
down_revision = '0006_api'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadline_rules',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('claimant_role', sa.String(length=32), nullable=False),
    sa.Column('anchor', sa.String(length=32), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('day_basis', sa.String(length=16), nullable=False),
    sa.Column('citation', sa.String(length=500), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', massingbill.models.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'state', 'kind', 'claimant_role', 'effective_from', name='uq_deadline_rule')
    )
    with op.batch_alter_table('deadline_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deadline_rules_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deadline_rules_state'), ['state'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_furnishing_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_furnishing_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notice_of_completion_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('notice_of_completion_date')
        batch_op.drop_column('last_furnishing_date')
        batch_op.drop_column('first_furnishing_date')

    with op.batch_alter_table('deadline_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deadline_rules_state'))
        batch_op.drop_index(batch_op.f('ix_deadline_rules_organization_id'))

    op.drop_table('deadline_rules')
    # ### end Alembic commands ###
