"""P10 spent handoff assertions

Revision ID: 0009_handoff
Revises: 0007_deadlines
Create Date: 2026-08-13 06:54:44.463886

"""
from alembic import op
import sqlalchemy as sa

# Custom column types live here. Autogenerate renders them fully qualified
# (massingbill.models.base.UtcDateTime), so the module must be importable or
# every generated migration fails with NameError on first run.
import massingbill.models.base  # noqa: F401


# revision identifiers, used by Alembic.
revision = '0009_handoff'
down_revision = '0007_deadlines'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spent_handoffs',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('used_at', massingbill.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spent_handoffs')
    # ### end Alembic commands ###
